# Generated by Django 5.2.9 on 2025-12-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
